/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CapitoliImport } from './routes/_capitoli'
import { Route as CapitoliCapitolo1PropsObjectIndexImport } from './routes/_capitoli/capitolo1/props-object/index'
import { Route as CapitoliCapitolo1PrimoComponenteIndexImport } from './routes/_capitoli/capitolo1/primo-componente/index'
import { Route as CapitoliCapitolo1JsInJsxIndexImport } from './routes/_capitoli/capitolo1/js-in-jsx/index'
import { Route as CapitoliCapitolo1HandleEventsIndexImport } from './routes/_capitoli/capitolo1/handle-events/index'
import { Route as CapitoliCapitolo1ConditionalRenderingIndexImport } from './routes/_capitoli/capitolo1/conditional-rendering/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const CapitoliCapitolo1IndexLazyImport = createFileRoute(
  '/_capitoli/capitolo1/',
)()

// Create/Update Routes

const CapitoliRoute = CapitoliImport.update({
  id: '/_capitoli',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CapitoliCapitolo1IndexLazyRoute = CapitoliCapitolo1IndexLazyImport.update(
  {
    path: '/capitolo1/',
    getParentRoute: () => CapitoliRoute,
  } as any,
).lazy(() =>
  import('./routes/_capitoli/capitolo1/index.lazy').then((d) => d.Route),
)

const CapitoliCapitolo1PropsObjectIndexRoute =
  CapitoliCapitolo1PropsObjectIndexImport.update({
    path: '/capitolo1/props-object/',
    getParentRoute: () => CapitoliRoute,
  } as any)

const CapitoliCapitolo1PrimoComponenteIndexRoute =
  CapitoliCapitolo1PrimoComponenteIndexImport.update({
    path: '/capitolo1/primo-componente/',
    getParentRoute: () => CapitoliRoute,
  } as any)

const CapitoliCapitolo1JsInJsxIndexRoute =
  CapitoliCapitolo1JsInJsxIndexImport.update({
    path: '/capitolo1/js-in-jsx/',
    getParentRoute: () => CapitoliRoute,
  } as any)

const CapitoliCapitolo1HandleEventsIndexRoute =
  CapitoliCapitolo1HandleEventsIndexImport.update({
    path: '/capitolo1/handle-events/',
    getParentRoute: () => CapitoliRoute,
  } as any)

const CapitoliCapitolo1ConditionalRenderingIndexRoute =
  CapitoliCapitolo1ConditionalRenderingIndexImport.update({
    path: '/capitolo1/conditional-rendering/',
    getParentRoute: () => CapitoliRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_capitoli': {
      preLoaderRoute: typeof CapitoliImport
      parentRoute: typeof rootRoute
    }
    '/_capitoli/capitolo1/': {
      preLoaderRoute: typeof CapitoliCapitolo1IndexLazyImport
      parentRoute: typeof CapitoliImport
    }
    '/_capitoli/capitolo1/conditional-rendering/': {
      preLoaderRoute: typeof CapitoliCapitolo1ConditionalRenderingIndexImport
      parentRoute: typeof CapitoliImport
    }
    '/_capitoli/capitolo1/handle-events/': {
      preLoaderRoute: typeof CapitoliCapitolo1HandleEventsIndexImport
      parentRoute: typeof CapitoliImport
    }
    '/_capitoli/capitolo1/js-in-jsx/': {
      preLoaderRoute: typeof CapitoliCapitolo1JsInJsxIndexImport
      parentRoute: typeof CapitoliImport
    }
    '/_capitoli/capitolo1/primo-componente/': {
      preLoaderRoute: typeof CapitoliCapitolo1PrimoComponenteIndexImport
      parentRoute: typeof CapitoliImport
    }
    '/_capitoli/capitolo1/props-object/': {
      preLoaderRoute: typeof CapitoliCapitolo1PropsObjectIndexImport
      parentRoute: typeof CapitoliImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CapitoliRoute.addChildren([
    CapitoliCapitolo1IndexLazyRoute,
    CapitoliCapitolo1ConditionalRenderingIndexRoute,
    CapitoliCapitolo1HandleEventsIndexRoute,
    CapitoliCapitolo1JsInJsxIndexRoute,
    CapitoliCapitolo1PrimoComponenteIndexRoute,
    CapitoliCapitolo1PropsObjectIndexRoute,
  ]),
])

/* prettier-ignore-end */
